version: '3'
services:
  nginx:
    container_name: magento2-training-nginx
    image: eterlabs/nginx-php74
    volumes:
      - ./code:/var/www/html:delegated
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf:cached
      - ./config/php.ini:/etc/php/7.4/fpm/php.ini:cached
      - ./config/auth.json:/root/.config/composer/auth.json
    ports:
      - 8071:80
    extra_hosts:
      - "host.docker.local:host-gateway"
    links:
      - elasticsearch
      - mariadb

  mariadb:
    image: mariadb:10.2
    restart: always
    container_name: magento2-training-mariadb
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: magento2
      MYSQL_USER: magento
      MYSQL_PASSWORD: magentopass

  phpmyadmin:
    container_name: magento2-training-phpmyadmin
    image: phpmyadmin
    restart: always
    ports:
      - 6071:80
    environment:
      - PMA_HOST=mariadb
    links:
      - mariadb

  elasticsearch:
    image: elasticsearch:7.12.0
    container_name: magento2-training-elasticsearch
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9210:9200